#!/bin/sh -e
#
# Setup a few parameters to make BIND9 settings a little safer (by ofuscation
# which is useless but required by PCI)

# Fix a few parameters which are considered unsafe by PCI
# (these are really just ofuscation of the DNS)
#
NAMED_CONF=/etc/bind/named.conf.options
DNS_OPTIONS=dns-options
EDIT_CONFIG=edit-config
NAMED_LOG_PATH=/var/log/named
OPENDKIM_CONF=/etc/opendkim.conf
OPENDKIM_DIR=/etc/opendkim
OPENDMARC_CONF=/etc/opendmarc.conf
OPENDMARC_DIR=/etc/opendmarc
OPENDMARC_DEFAULTS=/etc/default/opendmarc
POSTSRS_DEFAULTS=/etc/default/postsrsd

# Make a backup but only once (in case the .bak already exists, do not
# do a backup)
#
if test ! -f ${NAMED_CONF}.bak
then
    cp ${NAMED_CONF} ${NAMED_CONF}.bak
fi

# Setup the three most important values used to hide the DNS implementation
# (See SNAP-522)
#
${DNS_OPTIONS} -e 'options.version = none'   ${NAMED_CONF}
${DNS_OPTIONS} -e 'options.hostname = none'  ${NAMED_CONF}
${DNS_OPTIONS} -e 'options.server-id = none' ${NAMED_CONF}

# Setup the bogus network IP addresses
# (See SNAP-553)
#
${DNS_OPTIONS} -e 'acl[bogusnets]._ = 0.0.0.0/8;'      ${NAMED_CONF}
${DNS_OPTIONS} -e 'acl[bogusnets]._ = 192.0.2.0/24;'   ${NAMED_CONF}
${DNS_OPTIONS} -e 'acl[bogusnets]._ = 224.0.0.0/3;'    ${NAMED_CONF}

# The following may be used by the private network
#
#${DNS_OPTIONS} -e 'acl[bogusnets]._ = 10.0.0.0/8;'     ${NAMED_CONF}
#${DNS_OPTIONS} -e 'acl[bogusnets]._ = 172.16.0.0/12;'  ${NAMED_CONF}
#${DNS_OPTIONS} -e 'acl[bogusnets]._ = 192.168.0.0/16;' ${NAMED_CONF}

${DNS_OPTIONS} -e 'options.blackhole._ = bogusnets;' ${NAMED_CONF}

# For dynamic DNS features to work
#
${DNS_OPTIONS} -e 'options.allow-recursion._ = trusted-servers;' ${NAMED_CONF}
${DNS_OPTIONS} -e 'options.allow-notify._ = trusted-servers;' ${NAMED_CONF}
${DNS_OPTIONS} -e 'options.allow-transfer._ = trusted-servers;' ${NAMED_CONF}

# NEVER ADD allow-update HERE OR IT MAKES THE WHOLE SERVER A SLAVE
#${DNS_OPTIONS} -e 'options.allow-update._ = trusted-servers;' ${NAMED_CONF}
# No need for the "allow-new-zones", we create those
#${DNS_OPTIONS} -e 'options.allow-new-zones._ = true;' ${NAMED_CONF}

# Define a security log file
# (See SNAP-483)
#
${DNS_OPTIONS} -e 'logging.category[security]._ = security_file'      ${NAMED_CONF}
${DNS_OPTIONS} -e 'logging.channel[security_file].file = "'${NAMED_LOG_PATH}'/security.log" versions 3 size 30m' ${NAMED_CONF}
${DNS_OPTIONS} -e 'logging.channel[security_file].severity = dynamic' ${NAMED_CONF}
${DNS_OPTIONS} -e 'logging.channel[security_file].print-time = yes'   ${NAMED_CONF}

# Create the log folder, no rotation is required as the definition
# in the options already defines how many files and their size we
# accept (i.e. 3 files each of up to 30Mb)
#
if test ! -d ${NAMED_LOG_PATH}
then
    mkdir -p ${NAMED_LOG_PATH}
    chown bind:bind ${NAMED_LOG_PATH}
fi

# On our old server (16.04) the command line looked like this:
#
#    /usr/sbin/opendkim -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid -p inet:12345@localhost
#
# On newer system, the opendkim.conf can include all of these parameters.
#

mkdir -p ${OPENDKIM_DIR}
#${EDIT_CONFIG} --space ${OPENDKIM_CONF} Syslog yes
# The default UMask is 007 which I think would be better?
${EDIT_CONFIG} --space ${OPENDKIM_CONF} UMask 002
${EDIT_CONFIG} --space ${OPENDKIM_CONF} Socket inet:12345@localhost
#${EDIT_CONFIG} --space ${OPENDKIM_CONF} PidFile /run/opendkim/opendkim.pid
#${EDIT_CONFIG} --space ${OPENDKIM_CONF} OversignHeaders From
${EDIT_CONFIG} --space ${OPENDKIM_CONF} KeyTable ${OPENDKIM_DIR}/key_table
${EDIT_CONFIG} --space ${OPENDKIM_CONF} SigningTable ${OPENDKIM_DIR}/signing_table
${EDIT_CONFIG} --space ${OPENDKIM_CONF} ExternalIgnoreList ${OPENDKIM_DIR}/trusted_hosts
${EDIT_CONFIG} --space ${OPENDKIM_CONF} InternalHosts ${OPENDKIM_DIR}/trusted_hosts
${EDIT_CONFIG} --space ${OPENDKIM_CONF} AutoRestart yes
${EDIT_CONFIG} --space ${OPENDKIM_CONF} AutoRestartRate 10/1h
#${EDIT_CONFIG} --space ${OPENDKIM_CONF} Mode sv

${EDIT_CONFIG} --space ${OPENDMARC_CONF} Socket inet:54321@localhost
${EDIT_CONFIG} --space ${OPENDMARC_CONF} IgnoreHosts /etc/opendmarc/ignore_hosts
${EDIT_CONFIG} --space ${OPENDMARC_CONF} HistoryFile /run/opendmarc/opendmarc.dat

${EDIT_CONFIG} ${OPENDMARC_DEFAULTS} SOCKET inet:54321@localhost

MAILNAME=`cat /etc/mailname`
${EDIT_CONFIG} ${POSTSRS_DEFAULTS} SRS_DOMAIN ${MAILNAME}

# vim: ts=4 sw=4 et
